
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ config, lib, pkgs, ... }:

{

  imports = [
    ./docker.nix
    ./7zip.nix
  ];

  environment.etc.bahmni_enc = {
    target = "bahmni_enc";
    source = ./local/bahmni_enc;
    mode = "symlink";
  };

#  users.extraUsers.bahmni = {
#    isSystemUser = true;
#    createHome = true;
#    home = "/home/bahmni";
#    extraGroups = [ "docker" ];
#  };

#  systemd.services.bahmni-docker = {
#    enable = false;
#    description = "Bahmni containers";
#    requires = [ "docker.service" ];
#    after = [ "docker.service" ];
##    wantedBy = [ "multi-user.target" ];
#    serviceConfig = {
#      User = "bahmni";
##      WorkingDirectory = "/home/bahmni/bahmni-docker";
#      Restart = "always";
#      RestartSec = 10;
#      TimeoutSec = "infinity";
#      ExecStart = "${pkgs.docker_compose}/bin/docker-compose up";
#      ExecStop = "${pkgs.docker_compose}/bin/docker-compose down";
#    };
#  };

}

