
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ config, lib, pkgs, ... }:

{

  imports = [
    ./docker.nix
    ./7zip.nix
  ];

#  users.extraUsers.bahmni = {
#    isSystemUser = true;
#    createHome = true;
#    home = "/home/bahmni";
#    extraGroups = [ "docker" ];
#  };

}

