
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ config, lib, pkgs, ... }:

{

  imports = [
    ./docker.nix
    ./7zip.nix
  ];

  environment.etc.bahmni_enc = {
    enable = false;
    target = "bahmni_enc";
    source = ./local/bahmni_enc;
    mode = "0400";
    user = "root";
    group = "root";
  };

#  users.extraUsers.bahmni = {
#    isSystemUser = true;
#    createHome = true;
#    home = "/home/bahmni";
#    extraGroups = [ "docker" ];
#  };

}

