
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ config, lib, pkgs, ... }:

{

  environment.systemPackages = with pkgs; [
    git
    docker_compose
  ]; 

  boot.kernel.sysctl = {
    "vm.overcommit_memory" = 1;
    "net.core.somaxconn" = 65535;
  };

  virtualisation.docker.enable = true;
  virtualisation.docker.enableOnBoot = true;

  systemd.services.docker.wants = [ "network-online.target" ];
  systemd.services.docker.after = [ "network-online.target" ];

}

