
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ config, lib, pkgs, ... }:

{

  imports = [
    ./docker.nix
  ];

  users.extraUsers.easynut = {
    isSystemUser = true;
    createHome = true;
    home = "/home/easynut";
    extraGroups = [ "docker" ];
  };

}

