
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN A GIT REPO,       #
# PUSHED TO GITHUB AND MERGED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ config, lib, pkgs, ... }:

{

  environment.systemPackages = with pkgs; [
    git
    docker
    docker_compose
  ]; 

  boot.kernel.sysctl = {
    "vm.overcommit_memory" = 1;
    "net.core.somaxconn" = 65535;
  };

  virtualisation.docker.enable = true;
  virtualisation.docker.enableOnBoot = true;

  users.extraUsers.easynut = {
    isNormalUser = true;
    extraGroups = [ "networkmanager" "docker" ];
    hashedPassword = "$6$K4cr02qp0n7Nx2FN$SPLUgkWO13rlW516M55cb0IMPX3kuHI7vd/loVo8qoY/1uy027xSygQPvmF15f0tfULL6xfFNpSh3Q40Op1kj/";
  };

  users.extraUsers.msfocb = {
    extraGroups = [ "docker" ];
  };

  systemd.services.easynut-docker = {
    enable = true;
    description = "Easynut containers";
    requires = [ "docker.service" ];
    after = [ "docker.service" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      User = "easynut";
      WorkingDirectory = "/home/easynut/easynut-docker";
      Restart = "always";
      RestartSec = 10;
      TimeoutSec = "infinity";
      ExecStart = "${pkgs.docker_compose}/bin/docker-compose up";
      ExecStop = "${pkgs.docker_compose}/bin/docker-compose down";
    };
  };

}

