
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ config, lib, pkgs, ... }:

{

  imports = [
    ./docker.nix
  ];

  users.extraUsers.easynut = {
    isSystemUser = true;
    createHome = true;
    home = "/home/easynut";
    extraGroups = [ "docker" ];
  };

  systemd.services.easynut-docker = {
    enable = true;
    description = "Easynut containers";
    requires = [ "docker.service" ];
    after = [ "docker.service" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      User = "easynut";
      WorkingDirectory = "/home/easynut/easynut-docker";
      Restart = "always";
      RestartSec = 10;
      TimeoutSec = "infinity";
      ExecStart = "${pkgs.docker_compose}/bin/docker-compose up";
      ExecStop = "${pkgs.docker_compose}/bin/docker-compose down";
    };
  };

}

