
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ config, pkgs, lib, ... }:

{

  # sudo -u tunnel ssh-keygen -a 100 -t ed25519 -N "" -C "$(whoami)@${HOSTNAME}" -f ${HOME}/id_${HOSTNAME}

  users.extraUsers.tunnel = {
    isSystemUser = true;
    createHome = true;
    home = "/var/tunnel";
  };

  environment.etc.id_tunnel = {
    source = ./local/id_tunnel;
    mode = "0400";
    user = "tunnel";
    group = "tunnel";
  };

  systemd.services = let
    reverse_tunnel_config = [ { name = "google";  host = "msfrelay1.msfict.info"; }
                              { name = "ixelles"; host = "194.78.17.132"; } ];
    remote_forward_port = (import ./settings.nix).reverse_tunnel_forward_port;
    make_service = conf: {
      "autossh-reverse-tunnel-${conf.name}" = {
        enable = true;
        description = "AutoSSH reverse tunnel service to ensure resilient ssh access";
        after = [ "network.target" ];
        wantedBy = [ "multi-user.target" ];
        environment = {
          AUTOSSH_GATETIME = "0";
          AUTOSSH_PORT = "0";
        };
        serviceConfig = {
          User = "tunnel";
          Restart = "always";
          RestartSec = 10;
          ExecStart = ''${pkgs.autossh}/bin/autossh \
            -q -N \
            -o "ExitOnForwardFailure=yes" \
            -o "ServerAliveInterval=60" \
            -o "ServerAliveCountMax=3" \
            -o "ConnectTimeout=30" \
            -o "UpdateHostKeys=yes" \
            -o "StrictHostKeyChecking=no" \
            -o "IdentitiesOnly=yes" \
            -o "Compression=yes" \
            -o "ControlMaster=no" \
            -R ${remote_forward_port}:localhost:22 \
            -i /etc/id_tunnel \
            tunnel@${conf.host}
          '';
        };
      };
    };
  in
    lib.foldr (conf: services: services // (make_service conf)) {} reverse_tunnel_config;

}

