
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ config, pkgs, ... }:

{

  nixpkgs.config.allowUnfree = true;

  # Run "sudo teamviewer setup" afterwards to link
  # the teamviewer daemon to a teamviewer account.
  services.teamviewer.enable = true;

}

